tunnel: ${CLOUDFLARED_TUNNEL_ID}
credentials-file: /etc/cloudflared/${CLOUDFLARED_TUNNEL_ID}.json
ingress:
  - hostname: ${CLOUDFLARED_TUNNEL_HOSTNAME}
    service: http://postgrest:3000
  - service: http_status:404
